# Generated by Django 5.2 on 2025-10-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_created_date_alter_post_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['published_date', 'status']},
        ),
    ]
